/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Gestor.Gestor;
import Principal.Comprador;
import Principal.Producto;
import Principal.Vendedor;
import Vista.JPanel_Producto;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.BoxLayout;

/**
 *
 * @author treme
 */
public class JFrame_Comprador extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Comprador
     */
    private String id;
    private Comprador comprador;
    public JFrame_Comprador(String id) {
        this.id=id;
        this.comprador=Gestor.compradores.findComprador(id);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        JLabelUsuario.setText("Bienvenido: "+comprador.getNombre()+" "+comprador.getApellido1()+" "+comprador.getApellido2());
        JLabelID.setText("ID: "+comprador.getId());
        List<Producto>produc=Gestor.productos.findProductoEntities();
        int[][] coordenadas = {
            {0, 0},      // Producto 1
            {185, 0},    // Producto 2
            {370, 0},    // Producto 3
            {0, 195},    // Producto 4
            {185, 195},  // Producto 5
            {370, 195}   // Producto 6
         };
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        for (int i = 0; i < produc.size(); i++) {
              int x = coordenadas[i][0];
              int y = coordenadas[i][1];
                Producto nuevo = produc.get(i);
                JPanel_Producto nuevopanel = new JPanel_Producto(nuevo);
                nuevopanel.setBounds(x, y, 175, 185);
            
                // Añadir al JPanel1, no al JFrame
                     jPanel1.add(nuevopanel);
        
    }
    jPanel1.revalidate();
    jPanel1.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelUsuario = new javax.swing.JLabel();
        JLabelID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabelUsuario.setText("Bienvenido:");

        JLabelID.setText("ID:");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(JLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(JLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelUsuario)
                    .addComponent(JLabelID))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelID;
    private javax.swing.JLabel JLabelUsuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
