/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Gestor.Gestor;
import Principal.Comprador;
import Principal.Vendedor;

/**
 *
 * @author treme
 */
public class JFrame_Cuenta extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Cuenta
     */
    public JFrame_Cuenta() {

        initComponents();
        setResizable(false); //evita que se maximize el JFrame
        setLocationRelativeTo(null);// inicia el JFrame en el centro
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBTipodeCuenta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFContra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TFApellido1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TFApellido2 = new javax.swing.JTextField();
        BTRegresar = new javax.swing.JButton();
        BTCrear = new javax.swing.JButton();
        LabelEstado = new javax.swing.JLabel();
        LlMontoInicial = new javax.swing.JLabel();
        TFMontoInicial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CBTipodeCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comprador", "Vendedor" }));
        CBTipodeCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTipodeCuentaActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione tipo de cuenta");

        jLabel2.setText("Ingrese ID");

        TFID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFIDMouseClicked(evt);
            }
        });
        TFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFIDActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese Contraseña");

        jLabel4.setText("Ingrese Nombre");

        jLabel5.setText("Ingrese Primer Apellido");

        jLabel6.setText("Ingrese Segundo Apellido");

        BTRegresar.setText("Regresar");
        BTRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRegresarActionPerformed(evt);
            }
        });

        BTCrear.setText("Crear cuenta");
        BTCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCrearActionPerformed(evt);
            }
        });

        LabelEstado.setText("Estado: ");

        LlMontoInicial.setText("Ingrese Monto Incial");

        TFMontoInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFMontoInicialMouseClicked(evt);
            }
        });
        TFMontoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFMontoInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TFContra, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFID, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFApellido1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFApellido2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CBTipodeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))))
                                .addGap(138, 138, 138)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFMontoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(LlMontoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(BTRegresar)
                        .addGap(18, 18, 18)
                        .addComponent(BTCrear)))
                .addGap(338, 338, 338))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CBTipodeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LlMontoInicial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFMontoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(TFContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(LabelEstado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTRegresar)
                    .addComponent(BTCrear))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
        JFrame_Inicio regresar=new JFrame_Inicio();
        regresar.setVisible(true);
    }//GEN-LAST:event_BTRegresarActionPerformed

    private void BTCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCrearActionPerformed
        // TODO add your handling code here:
        String tipo=(String) CBTipodeCuenta.getSelectedItem();
        String id=TFID.getText();
        String contra=TFContra.getText();
        String nombre=TFNombre.getText();
        String apellido1=TFApellido1.getText();
        String apellido2=TFApellido2.getText();

        if(tipo.contains("Comprador")){
            String auxmontoinicial=TFMontoInicial.getText();
            double montoinicial=Double.parseDouble(auxmontoinicial);
            Comprador nuevo=new Comprador(montoinicial,id,contra,nombre,apellido1,apellido2);
            Gestor.compradores.create(nuevo);
        }else if(tipo.contains("Vendedor")){
            Vendedor nuevo=new Vendedor(id,contra,nombre,apellido1,apellido2);
            Gestor.vendedores.create(nuevo);
        }
        TFID.setText("");
        TFContra.setText("");
        TFNombre.setText("");
        TFApellido1.setText("");
        TFApellido2.setText("");
        LabelEstado.setText("Estado: Cuenta Creada del tipo "+tipo);

    }//GEN-LAST:event_BTCrearActionPerformed

    private void TFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFIDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TFIDActionPerformed

    private void TFIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFIDMouseClicked
        // TODO add your handling code here:
        LabelEstado.setText("Estado:");
    }//GEN-LAST:event_TFIDMouseClicked

    private void CBTipodeCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTipodeCuentaActionPerformed
        // TODO add your handling code here:
        String tipo=(String) CBTipodeCuenta.getSelectedItem();
        if(tipo.contains("Vendedor")){
            LlMontoInicial.setVisible(false);
            TFMontoInicial.setVisible(false);
        }else{
            LlMontoInicial.setVisible(true);
            TFMontoInicial.setVisible(true);
        }
    }//GEN-LAST:event_CBTipodeCuentaActionPerformed

    private void TFMontoInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFMontoInicialMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMontoInicialMouseClicked

    private void TFMontoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFMontoInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMontoInicialActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCrear;
    private javax.swing.JButton BTRegresar;
    private javax.swing.JComboBox<String> CBTipodeCuenta;
    private javax.swing.JLabel LabelEstado;
    private javax.swing.JLabel LlMontoInicial;
    private javax.swing.JTextField TFApellido1;
    private javax.swing.JTextField TFApellido2;
    private javax.swing.JTextField TFContra;
    private javax.swing.JTextField TFID;
    private javax.swing.JTextField TFMontoInicial;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
