/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Gestor.Gestor;
import Modelo.Imagen;
import Principal.Producto;

/**
 *
 * @author treme
 */
public class JPanel_Producto extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Producto
     */
    private Producto producto;
    public JPanel_Producto(Producto producto) {
        this.producto=producto;
        initComponents();
        LlNombre.setText(producto.getNombre());
        LlDescri.setText(producto.getDescripcion());
        double auxprecio=producto.getPrecio();
        String precioaux=Double.toString(auxprecio);
        LlPrecio.setText(precioaux);
        LlMarca.setText(producto.getMarca());
        int auxstock=producto.getStock();
        String stockaux=Integer.toString(auxstock);
        LlStock.setText(stockaux);
        for(int i=1;i<=producto.getStock();i++){
            String aux = Integer.toString(i);
            CBStock.addItem(aux);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LlNombre = new javax.swing.JLabel();
        LlDescri = new javax.swing.JLabel();
        LlPrecio = new javax.swing.JLabel();
        LlMarca = new javax.swing.JLabel();
        LlStock = new javax.swing.JLabel();
        imagen1 = new Modelo.Imagen();
        CBStock = new javax.swing.JComboBox<>();
        BTComprar = new javax.swing.JButton();

        LlNombre.setText("Nombre");

        LlDescri.setText("descipcion");

        LlPrecio.setText("precio");

        LlMarca.setText("marca");

        LlStock.setText("Stock");

        imagen1.setRuta("/Imagenes/producto.png");

        CBStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBStockActionPerformed(evt);
            }
        });

        BTComprar.setText("Comprar");
        BTComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LlPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(LlMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LlDescri, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LlStock))
                            .addComponent(LlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CBStock, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTComprar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LlStock)
                    .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(LlNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LlDescri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LlPrecio)
                    .addComponent(LlMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTComprar))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CBStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBStockActionPerformed

    private void BTComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTComprarActionPerformed
        // TODO add your handling code here:
        String text=(String) CBStock.getSelectedItem();
        int redu=Integer.parseInt(text);
        int stock2=producto.getStock();
        int nuevostock=stock2-redu;
        String aux=Integer.toString(nuevostock);
        LlStock.setText(aux);
        producto.setStock(nuevostock);
        Gestor.productos.edit(producto);
        CBStock.removeAllItems();
        for(int i=1;i<=producto.getStock();i++){
            String aux4 = Integer.toString(i);
            CBStock.addItem(aux4);
        }
    }//GEN-LAST:event_BTComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTComprar;
    private javax.swing.JComboBox<String> CBStock;
    private javax.swing.JLabel LlDescri;
    private javax.swing.JLabel LlMarca;
    private javax.swing.JLabel LlNombre;
    private javax.swing.JLabel LlPrecio;
    private javax.swing.JLabel LlStock;
    private Modelo.Imagen imagen1;
    // End of variables declaration//GEN-END:variables
}
