/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Gestor.Gestor;
import static Gestor.Gestor.productos;
import Principal.Comprador;
import Principal.Producto;
import Principal.Vendedor;
import Vista.JPanel_Producto;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author treme
 */
public class JFrame_Comprador extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Comprador
     */
    private String id;
    private Comprador comprador;
    private CardLayout layout;
    private JPanel panelContenedor;
    public JFrame_Comprador(String id) {
        this.id=id;
        this.comprador=Gestor.compradores.findComprador(id);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        layout = new CardLayout();
        panelContenedor = new JPanel(layout);
        panelContenedor.setBounds(102, 66, 696, 510);
        add(panelContenedor);
        panelContenedor.add(JSPVerProductos, "comprar");
        JPanel_Boleta panelBoleta = new JPanel_Boleta(comprador);
        panelContenedor.add(panelBoleta, "boleta");
        panelContenedor.add(new JPanel_EditarCuenta(comprador), "cuenta");
        JPanel_Carrito panelCarrito=new JPanel_Carrito(comprador,panelBoleta);
        panelContenedor.add(panelCarrito, "carrito");
        JLabelUsuario.setText("Bienvenido: "+comprador.getNombre()+" "+comprador.getApellido1()+" "+comprador.getApellido2());
        JLabelID.setText("ID: "+comprador.getId());
        List<Producto>produc=Gestor.productos.findProductoEntities();
        int columnas = 3;
        int filas = (int) Math.ceil(produc.size() / (double) columnas);
        JPComprarProductos.setLayout(new GridLayout(filas, columnas, 0, 0)); // 0px de separación
        for (Producto prod : produc) {
            JPanel_Producto panelProd = new JPanel_Producto(prod,comprador,panelBoleta,panelCarrito);
            panelProd.setPreferredSize(new Dimension(175, 185)); // Tamaño uniforme
            JPComprarProductos.add(panelProd);
        }
         JPComprarProductos.revalidate();
        JPComprarProductos.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelUsuario = new javax.swing.JLabel();
        JLabelID = new javax.swing.JLabel();
        JSPVerProductos = new javax.swing.JScrollPane();
        JPComprarProductos = new javax.swing.JPanel();
        BTVerProductos = new javax.swing.JButton();
        BTBoleta = new javax.swing.JButton();
        BTCuenta = new javax.swing.JButton();
        BTCarrito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabelUsuario.setText("Bienvenido:");

        JLabelID.setText("ID:");

        JPComprarProductos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JPComprarProductosLayout = new javax.swing.GroupLayout(JPComprarProductos);
        JPComprarProductos.setLayout(JPComprarProductosLayout);
        JPComprarProductosLayout.setHorizontalGroup(
            JPComprarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        JPComprarProductosLayout.setVerticalGroup(
            JPComprarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        JSPVerProductos.setViewportView(JPComprarProductos);

        BTVerProductos.setText("Comprar");
        BTVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTVerProductosActionPerformed(evt);
            }
        });

        BTBoleta.setText("Boleta");
        BTBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBoletaActionPerformed(evt);
            }
        });

        BTCuenta.setText("Cuenta");
        BTCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCuentaActionPerformed(evt);
            }
        });

        BTCarrito.setText("Carrito");
        BTCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(JLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BTVerProductos)
                        .addComponent(BTBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BTCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(4, 4, 4)))
                    .addComponent(BTCarrito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JSPVerProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelUsuario)
                    .addComponent(JLabelID))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JSPVerProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(BTVerProductos)
                        .addGap(55, 55, 55)
                        .addComponent(BTCarrito)
                        .addGap(36, 36, 36)
                        .addComponent(BTBoleta)
                        .addGap(61, 61, 61)
                        .addComponent(BTCuenta)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBoletaActionPerformed
        // TODO add your handling code here:
         layout.show(panelContenedor, "boleta");
         Gestor.itemstemp.clear();

    }//GEN-LAST:event_BTBoletaActionPerformed

    private void BTCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCuentaActionPerformed
        // TODO add your handling code here:
         layout.show(panelContenedor, "cuenta");
         Gestor.itemstemp.clear();
    }//GEN-LAST:event_BTCuentaActionPerformed

    private void BTVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTVerProductosActionPerformed
        // TODO add your handling code here:
         layout.show(panelContenedor, "comprar");
         Gestor.itemstemp.clear();
    }//GEN-LAST:event_BTVerProductosActionPerformed

    private void BTCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCarritoActionPerformed
        // TODO add your handling code here:
        layout.show(panelContenedor, "carrito");
    }//GEN-LAST:event_BTCarritoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTBoleta;
    private javax.swing.JButton BTCarrito;
    private javax.swing.JButton BTCuenta;
    private javax.swing.JButton BTVerProductos;
    private javax.swing.JLabel JLabelID;
    private javax.swing.JLabel JLabelUsuario;
    private javax.swing.JPanel JPComprarProductos;
    private javax.swing.JScrollPane JSPVerProductos;
    // End of variables declaration//GEN-END:variables
}
