/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Gestor.Gestor;
import Principal.Comprador;
import Principal.Usuario;
import Principal.Vendedor;
import Vista.JFrame_Comprador;
import Vista.JFrame_Cuenta;
import Vista.JFrame_Vendedor;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author treme
 */
public class JFrame_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Inicio
     */
    public JFrame_Inicio() {
        initComponents();
        setResizable(false); //Permite que no se pueda maximizar el JFrame
        setLocationRelativeTo(null); //Permite que el JFrame este centrado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFContra = new javax.swing.JPasswordField();
        BTIniciar = new javax.swing.JButton();
        BTRegistrar = new javax.swing.JButton();
        imagen1 = new Modelo.Imagen();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INICIAR SESIÓN");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("USUARIO");

        TFUsuario.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        TFUsuario.setText("Ingrese su nombre de usario");
        TFUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFUsuarioMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CONTRASEÑA");

        TFContra.setText("********");
        TFContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFContraMousePressed(evt);
            }
        });
        TFContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFContraActionPerformed(evt);
            }
        });

        BTIniciar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        BTIniciar.setForeground(new java.awt.Color(0, 0, 0));
        BTIniciar.setText("INICIAR");
        BTIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTIniciarActionPerformed(evt);
            }
        });

        BTRegistrar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        BTRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        BTRegistrar.setText("REGISTRAR");
        BTRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRegistrarActionPerformed(evt);
            }
        });

        imagen1.setRuta("/Imagenes/logo.png");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(TFUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(TFContra))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFUsuarioMousePressed
        // TODO add your handling code here:
         if(TFUsuario.getText().equals("Ingrese su nombre de usario")){
        TFUsuario.setText("");
        TFUsuario.setForeground(Color.black);
         }
        if(TFContra.getText().equals("")){
        TFContra.setText("********");
        TFContra.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TFUsuarioMousePressed

    private void TFContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFContraActionPerformed

    private void TFContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFContraMousePressed
        // TODO add your handling code here:
        if(TFContra.getText().equals("********")){
        TFContra.setText("");
        TFContra.setForeground(Color.black);
        }
        if(TFUsuario.getText().equals("")){
        TFUsuario.setText("Ingrese su nombre de usario");
        TFUsuario.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_TFContraMousePressed

    private void BTRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRegistrarActionPerformed
        // TODO add your handling code here:
        dispose(); //Permite supender el JFrame
        JFrame_Cuenta iniciar=new JFrame_Cuenta(); //Instaciamos como si fuera un objeto
        iniciar.setVisible(true); //Hacemo visible el JFrame de registrar
    }//GEN-LAST:event_BTRegistrarActionPerformed

    private void BTIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTIniciarActionPerformed
        // TODO add your handling code here:
        String id=TFUsuario.getText(); //Obtener el ID que se escrito en JFrame
        List<Comprador>comp=Gestor.compradores.findCompradorEntities(); // Obtenemos  la List compradores
        List<Vendedor>vend=Gestor.vendedores.findVendedorEntities(); // Obtemos la List Vendedores
        
        for (int i = 0; i < comp.size(); i++) {
            Comprador e = (Comprador) comp.get(i); //Comprador E aux
            if (e.getId().contains(id)) { //Por si es igual ID
                dispose();
                JFrame_Comprador iniciar=new JFrame_Comprador(e.getId()); //Si es ID valido esta parte iniciar el JFrame Comprador
                iniciar.setVisible(true);
                break; 
                }
            }
        for (int i = 0; i < vend.size(); i++) {
            Vendedor e = (Vendedor) vend.get(i);
            if (e.getId().contains(id)) {
                dispose();
                JFrame_Vendedor iniciar=new JFrame_Vendedor(e.getId()); //Le paso el ID a mis otros JFrame
                iniciar.setVisible(true); //Si es ID valido esta parte iniciar el JFrame Vendedor
                break; 
                }
            }
    }//GEN-LAST:event_BTIniciarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTIniciar;
    private javax.swing.JButton BTRegistrar;
    private javax.swing.JPasswordField TFContra;
    private javax.swing.JTextField TFUsuario;
    private Modelo.Imagen imagen1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
