/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Gestor.Gestor;
import Principal.Producto;
import Principal.Vendedor;
import Vista.JFrame_Inicio;
import java.awt.Rectangle;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author treme
 */
public class JFrame_Vendedor extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Vendedor
     */
    private String id;
    private Vendedor vendedor;
    public JFrame_Vendedor(String id) {
        this.id=id;
        this.vendedor=Gestor.vendedores.findVendedor(id);
        initComponents();
        setResizable(false); //evita que se maximize el JFrame
        setLocationRelativeTo(null);// inicia el JFrame en el centro
        JLabelVendedor.setText(vendedor.getNombre()+" "+vendedor.getApellido1()+" "+vendedor.getApellido2());
        JLabelID.setText("ID: "+vendedor.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPAgregarProductos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFDescrip = new javax.swing.JTextField();
        TFID = new javax.swing.JTextField();
        TFMarca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TFStock = new javax.swing.JTextField();
        BTRegresar = new javax.swing.JButton();
        BTAgregarProducto = new javax.swing.JButton();
        JLabelEstado = new javax.swing.JLabel();
        ImagenProducto = new Modelo.Imagen();
        jLabel1 = new javax.swing.JLabel();
        JLabelVendedor = new javax.swing.JLabel();
        JLabelID = new javax.swing.JLabel();
        BTAgregarProductos = new javax.swing.JButton();
        BTEditarProductos = new javax.swing.JButton();
        BTCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Ingrese descripcion");

        jLabel3.setText("Ingrese nombre");

        jLabel5.setText("Ingrese precio");

        jLabel6.setText("Ingrese marca");

        jLabel2.setText("Ingrese ID");

        jLabel7.setText("Ingrese stock");

        BTRegresar.setText("Regresar");
        BTRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRegresarActionPerformed(evt);
            }
        });

        BTAgregarProducto.setText("Agregar producto");
        BTAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTAgregarProductoActionPerformed(evt);
            }
        });

        JLabelEstado.setText("Estado:");

        ImagenProducto.setRuta("/Imagenes/producto.png");
        ImagenProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenProductoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPAgregarProductosLayout = new javax.swing.GroupLayout(JPAgregarProductos);
        JPAgregarProductos.setLayout(JPAgregarProductosLayout);
        JPAgregarProductosLayout.setHorizontalGroup(
            JPAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPAgregarProductosLayout.createSequentialGroup()
                .addGroup(JPAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPAgregarProductosLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(ImagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPAgregarProductosLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addGroup(JPAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPAgregarProductosLayout.createSequentialGroup()
                                .addComponent(BTRegresar)
                                .addGap(59, 59, 59)
                                .addComponent(BTAgregarProducto))
                            .addGroup(JPAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TFStock, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TFMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPAgregarProductosLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TFNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TFID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TFDescrip, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TFPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(1197, 1197, 1197)))
        );
        JPAgregarProductosLayout.setVerticalGroup(
            JPAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPAgregarProductosLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(ImagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(TFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(JLabelEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTRegresar)
                    .addComponent(BTAgregarProducto))
                .addGap(27, 27, 27))
            .addGroup(JPAgregarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPAgregarProductosLayout.createSequentialGroup()
                    .addGap(241, 241, 241)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(TFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(TFDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(TFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        jLabel1.setText("Bienvenido:");

        JLabelVendedor.setText("-");

        JLabelID.setText("ID:");

        BTAgregarProductos.setText("Agregar Productos");
        BTAgregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTAgregarProductosActionPerformed(evt);
            }
        });

        BTEditarProductos.setText("Editar Productos");
        BTEditarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEditarProductosActionPerformed(evt);
            }
        });

        BTCuenta.setText("Cuenta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BTAgregarProductos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTEditarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLabelVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(JLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(178, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPAgregarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JLabelVendedor)
                    .addComponent(JLabelID))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(BTAgregarProductos)
                        .addGap(101, 101, 101)
                        .addComponent(BTEditarProductos)
                        .addGap(113, 113, 113)
                        .addComponent(BTCuenta)
                        .addContainerGap(155, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPAgregarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagenProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenProductoMouseClicked
        // TODO add your handling code here:
        String ruta="";
        JFileChooser jFileChooser=new JFileChooser();
        FileNameExtensionFilter filtrado=new FileNameExtensionFilter("PNG","png");
        jFileChooser.setFileFilter(filtrado);
        
        int respuesta= jFileChooser.showOpenDialog(this);
        
        if(respuesta== JFileChooser.APPROVE_OPTION){
            ruta=jFileChooser.getSelectedFile().getPath();
            ImagenProducto.setRuta(ruta);
            ImagenProducto.repaint();
        }
        
    }//GEN-LAST:event_ImagenProductoMouseClicked

    private void BTAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAgregarProductoActionPerformed
        // TODO add your handling code here:
        String id=TFID.getText();
        String nombre=TFNombre.getText();
        String descri=TFDescrip.getText();
        String aux=TFPrecio.getText();
        double precio=Double.parseDouble(aux);
        String marca=TFMarca.getText();
        String aux2=TFStock.getText();
        int stock=Integer.parseInt(aux2);
        Producto nuevo=new Producto(id,nombre,descri,precio,marca,stock);
        Gestor.productos.create(nuevo);
        TFID.setText("");
        TFNombre.setText("");
        TFDescrip.setText("");
        TFPrecio.setText("");
        TFMarca.setText("");
        TFStock.setText("");
        JLabelEstado.setText("Estado: Producto agregado");
        ImagenProducto.setRuta("/Imagenes/producto.png");
        ImagenProducto.repaint();
    }//GEN-LAST:event_BTAgregarProductoActionPerformed

    private void BTRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
        JFrame_Inicio regresar=new JFrame_Inicio();
        regresar.setVisible(true);
    }//GEN-LAST:event_BTRegresarActionPerformed

    private void BTAgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAgregarProductosActionPerformed
        // TODO add your handling code here:
        //editar.setVisible(false);

    }//GEN-LAST:event_BTAgregarProductosActionPerformed

    private void BTEditarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEditarProductosActionPerformed
        // TODO add your handling code here:
        /*List<Producto>productos=Gestor.productos.findProductoEntities();
        JPEditarProducto editar=new JPEditarProducto(productos);
        JPAgregarProductos.setVisible(false);
        
        editar.setBounds(187, 72, 600, 507);
        add(editar);
        editar.setVisible(true);*/
        
        
    }//GEN-LAST:event_BTEditarProductosActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTAgregarProducto;
    private javax.swing.JButton BTAgregarProductos;
    private javax.swing.JButton BTCuenta;
    private javax.swing.JButton BTEditarProductos;
    private javax.swing.JButton BTRegresar;
    private Modelo.Imagen ImagenProducto;
    private javax.swing.JLabel JLabelEstado;
    private javax.swing.JLabel JLabelID;
    private javax.swing.JLabel JLabelVendedor;
    private javax.swing.JPanel JPAgregarProductos;
    private javax.swing.JTextField TFDescrip;
    private javax.swing.JTextField TFID;
    private javax.swing.JTextField TFMarca;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFPrecio;
    private javax.swing.JTextField TFStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
