/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Gestor.Gestor;
import Principal.CarritoItem;
import Principal.Producto;
import java.awt.Label;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author treme
 */
public class JPanel_Items extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Items
     */
    private CarritoItem item;
    private JLabel total;
    public JPanel_Items(CarritoItem item,JLabel total) {
        initComponents();
        this.item=item;
        this.total=total;
         if (item.getProducto().getImagen() != null) {
            ImagenItem.setImagenBytes(item.getProducto().getImagen());
        } else {
            ImagenItem.setRuta("/Imagenes/producto.png"); // Imagen por defecto
        }
        String cantidad=Integer.toString(item.getCantidad());
        LlCantidad.setText(cantidad);
        LlNombre.setText(item.getProducto().getNombre());
        LlDescrip.setText(item.getProducto().getDescripcion());
        Double auxsubtotal=item.Subtotal();
        String subtotal=Double.toString(auxsubtotal);
        LlSubtotal.setText(subtotal);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagenItem = new Modelo.Imagen();
        LlNombre = new javax.swing.JLabel();
        LlDescrip = new javax.swing.JLabel();
        LlCantidad = new javax.swing.JLabel();
        RBItems = new javax.swing.JRadioButton();
        LlSubtotal = new javax.swing.JLabel();

        ImagenItem.setRuta("/Imagenes/producto.png");

        LlNombre.setText("Nombre");

        LlDescrip.setText("Descripción");

        LlCantidad.setText("Cantidad");

        RBItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBItemsActionPerformed(evt);
            }
        });

        LlSubtotal.setText("Subtotal:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(LlCantidad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ImagenItem, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LlDescrip)
                    .addComponent(LlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(LlSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(RBItems)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LlCantidad)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LlNombre)
                                .addGap(10, 10, 10)
                                .addComponent(LlDescrip))
                            .addComponent(ImagenItem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LlSubtotal)
                            .addComponent(RBItems))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RBItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBItemsActionPerformed
        // TODO add your handling code here:
        if(RBItems.isSelected()){
            Gestor.carritotemp.agregarItem(item);
            double total1=Gestor.carritotemp.calcularTotal();
            total.setText("Total: "+total1);
    }else{
            Gestor.carritotemp.quitarItem(item);
            double total1=Gestor.carritotemp.calcularTotal();
            total.setText("Total: "+total1);
        }
        
    }//GEN-LAST:event_RBItemsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Modelo.Imagen ImagenItem;
    private javax.swing.JLabel LlCantidad;
    private javax.swing.JLabel LlDescrip;
    private javax.swing.JLabel LlNombre;
    private javax.swing.JLabel LlSubtotal;
    private javax.swing.JRadioButton RBItems;
    // End of variables declaration//GEN-END:variables
}
