/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Gestor.Gestor;
import static Gestor.Gestor.carritotemp;
import Principal.CarritoItem;
import Principal.Comprador;
import Principal.Producto;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.BoxLayout;

/**
 *
 * @author treme
 */
public class JPanel_Carrito extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Items
     */
    private Comprador comprador;
    private List<CarritoItem>items;
    private JPanel_Boleta panelverBoleta;
    public JPanel_Carrito(Comprador comprador,JPanel_Boleta panelVerBoleta) {
        initComponents();
        this.comprador=comprador;
        this.panelverBoleta = panelVerBoleta;
        this.items=Gestor.itemstemp;
        JPItems.setLayout(new BoxLayout(JPItems, BoxLayout.Y_AXIS));
        for(CarritoItem item:items){
            JPanel_Items nuevo=new JPanel_Items(item,LlTotal);
            JPItems.add(nuevo);
        }
        JPItems.revalidate();
        JPItems.repaint();
    }
    public void ActualizarCarrito(){
        for(CarritoItem item:items){
            JPanel_Items nuevo=new JPanel_Items(item,LlTotal);
            JPItems.add(nuevo);
        }
        JPItems.revalidate();
        JPItems.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SPVerItems = new javax.swing.JScrollPane();
        JPItems = new javax.swing.JPanel();
        LlTotal = new javax.swing.JLabel();
        BTComprar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(696, 510));

        javax.swing.GroupLayout JPItemsLayout = new javax.swing.GroupLayout(JPItems);
        JPItems.setLayout(JPItemsLayout);
        JPItemsLayout.setHorizontalGroup(
            JPItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );
        JPItemsLayout.setVerticalGroup(
            JPItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        SPVerItems.setViewportView(JPItems);

        LlTotal.setText("Total:");

        BTComprar.setText("Comprar");
        BTComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(SPVerItems, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(LlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(BTComprar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(SPVerItems, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LlTotal)
                    .addComponent(BTComprar))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTComprarActionPerformed
        // TODO add your handling code here:
        comprador.setCarrito(Gestor.carritotemp);
        Gestor.compradores.edit(comprador);
        panelverBoleta.actualizarBoleta();
        List<CarritoItem>itemsaux=Gestor.carritotemp.getItems();
        for(CarritoItem itaux:itemsaux){
            String idaux=itaux.getProducto().getId();
            Producto editar=Gestor.productos.findProducto(idaux);
            int stockactual=editar.getStock();
            int stockreduc=itaux.getCantidad();
            int nuevostock=stockactual-stockreduc;
            editar.setStock(nuevostock);
            Gestor.productos.edit(editar);
        }
        Gestor.itemstemp.clear();
        ActualizarCarrito();
        
    }//GEN-LAST:event_BTComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTComprar;
    private javax.swing.JPanel JPItems;
    private javax.swing.JLabel LlTotal;
    private javax.swing.JScrollPane SPVerItems;
    // End of variables declaration//GEN-END:variables
}
