/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Gestor.Gestor;
import Principal.Comprador;
import Principal.Usuario;
import Principal.Vendedor;

/**
 *
 * @author treme
 */
public class JPanel_EditarCuenta extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_CuentaVendedor
     */
    private Usuario usuario;
    public JPanel_EditarCuenta(Usuario usuario) {
        this.usuario=usuario;        
        initComponents();
        if (usuario instanceof Vendedor) {
            LlMonto.setVisible(false);
            TFMonto.setVisible(false);            
        }
        LlID.setText(usuario.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LlID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFContra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TFApellido2 = new javax.swing.JTextField();
        BTModificarCuenta = new javax.swing.JButton();
        LlEstado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFApellido1 = new javax.swing.JTextField();
        LlMonto = new javax.swing.JLabel();
        TFMonto = new javax.swing.JTextField();

        LlID.setText("ID:");

        jLabel2.setText("Ingrese contraseña a cambiar");

        TFContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFContraActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese Nombre a cambiar");

        jLabel4.setText("Ingrese Ingrese segundo apellido a cambiar");

        BTModificarCuenta.setText("Cambiar");
        BTModificarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTModificarCuentaActionPerformed(evt);
            }
        });

        LlEstado.setText("Estado:");

        jLabel6.setText("Ingrese primer apellido a cambiar");

        LlMonto.setText("Ingrese monto a cambiar");

        TFMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFMontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTModificarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LlID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TFContra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                            .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LlMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFMonto))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(LlEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(LlID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LlMonto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(15, 15, 15)
                .addComponent(TFApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(LlEstado)
                .addGap(27, 27, 27)
                .addComponent(BTModificarCuenta)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFContraActionPerformed
        // TODO add your handling code here:
        LlEstado.setText("Estado:");
        LlEstado.revalidate();
        LlEstado.repaint();
    }//GEN-LAST:event_TFContraActionPerformed

    private void TFMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFMontoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TFMontoActionPerformed

    private void BTModificarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTModificarCuentaActionPerformed
        // TODO add your handling code here:
        String id=LlID.getText();
        String contra=TFContra.getText();
        String nombre=TFNombre.getText();
        String apellido1=TFApellido1.getText();
        String apellido2=TFApellido2.getText();
         if (usuario instanceof Vendedor){
             Vendedor nuevo=Gestor.vendedores.findVendedor(id);
             nuevo.setContrania(contra);
             nuevo.setNombre(nombre);
             nuevo.setApellido1(apellido1);
             nuevo.setApellido2(apellido2);
             Gestor.vendedores.edit(nuevo);
         }
         if (usuario instanceof Comprador){
             String aux=TFMonto.getText();
             Double monto=Double.parseDouble(aux);
             Comprador nuevo=Gestor.compradores.findComprador(id);
             nuevo.setContrania(contra);
             nuevo.setNombre(nombre);
             nuevo.setApellido1(apellido1);
             nuevo.setApellido2(apellido2);
             nuevo.setDinero(monto);
             Gestor.compradores.edit(nuevo);
             TFMonto.setText("");
         }
         TFContra.setText("");
         TFContra.setText("");
         TFNombre.setText("");
         TFApellido1.setText("");
         TFApellido2.setText("");
         LlEstado.setText("Estado: Cuenta Actualizada");
         
    }//GEN-LAST:event_BTModificarCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTModificarCuenta;
    private javax.swing.JLabel LlEstado;
    private javax.swing.JLabel LlID;
    private javax.swing.JLabel LlMonto;
    private javax.swing.JTextField TFApellido1;
    private javax.swing.JTextField TFApellido2;
    private javax.swing.JTextField TFContra;
    private javax.swing.JTextField TFMonto;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
